name: Secure DevSecOps Pipeline

on: [push]

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Security Tools
        run: pip install bandit

      - name: Run SAST Scan & Generate Report
        # هنا نخبر Bandit أن يحفظ النتائج في ملف نصي اسمه report.txt
        # استخدمنا '|| true' لكي لا يتوقف النظام عند اكتشاف ثغرة، بل يكمل لتوليد التقرير
        run: bandit -r app.py -f txt -o security_report.txt || true

      - name: Upload Security Report
        # هذه الخطوة ستقوم برفع الملف لكي تستطيع تحميله من المتصفح
        uses: actions/upload-artifact@v4
        with:
          name: Security-Analysis-Report
          path: security_report.txt
