name: Secure DevSecOps Pipeline

on: [push]

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # ضروري لفحص تاريخ الكود بحثاً عن الأسرار

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Security Tools
        run: pip install bandit

      - name: Run Static Analysis (SAST)
        run: bandit -r app.py

      - name: Run Secret Scan
        # سنستخدم أداة TruffleHog الرسمية كخطوة جاهزة
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
