name: Secure DevSecOps Pipeline

on: [push] # يشتغل تلقائياً عند كل رفع كود

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Security Tools
        run: pip install bandit

      - name: Run Bandit Security Scan
        # هنا راح نفحص ملف app.py اللي رفعناه ونطلع تقرير بالثغرات
        run: bandit -r app.py
